version: '3.2'

networks:
  backend:

services:
  # engiemainapi:
  #   image: engie/intradaydashboard
  #   build: 
  #     context: ..\src\IntradayDashboard\IntradayDashboard.WebApi
  #     dockerfile: Dockerfile
  #   environment: 
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   container_name: engiewebapp
  #   ports:
  #     - "7985:80"
  #   depends_on:
  #     - engiemssqlserver
  #     - engierabbitmq
  #     - engieredis
    # restart: always
      
  engiemssqlserver:
    image: microsoft/mssql-server-linux
    volumes:
      - .\mssql:/var/opt/mssql
      - .\backups:/var/backups
    environment:
      - MSSQL_SA_PASSWORD=GitGood*0987654321
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1420:1433"
    restart: always

  engierabbitmq:
     image: rabbitmq:3-management
     container_name: engierabbitmq
     hostname: engierabbitmq
     ports:
        - "15672:15672"
        - "5672:5672"
        - "5671:5671"
     volumes:
        - ~/engierabbitmq:/var/lib/rabbitmq/mnesia
     restart: always
     
  engieredis:
     image: redis
     container_name: engieredisdb
     ports:
      - "6375:6379"  
     networks:
      - backend
     restart: always